# pytest.ini
[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression : Regression scope
    smoke : Smoke TCs
    registration : TCs for registration
    critical : For critical TCs
    authorization : TCs for authorization scope
    flaky : For not stable tests
    negative_tc : Negative TCs